FROM registry.fedoraproject.org/fedora:30

RUN dnf install -y git make

ENV HOME=/home/test-user \
    PYTHONDONTWRITEBYTECODE=1

RUN useradd -u 1000 -d ${HOME} test-user

WORKDIR ${HOME}

COPY Makefile ${HOME}/
COPY tests/requirements.txt ${HOME}/tests/
RUN pip3 install -r tests/requirements.txt
COPY tests/ ${HOME}/tests/
RUN chown -R 1000 ${HOME}

COPY setup.py setup.cfg /src/
# setuptools-scm
COPY .git/ /src/.git/
COPY release_bot/ /src/release_bot/
RUN cd /src/ && pip3 install . && rm -rf /src/

USER 1000

CMD make test
